### ISSUE TITLE
iwlwifi fails to load on UEK kernel

### ISSUE THREAD

**Issue by bah-mikerosenblum** [oracle/oracle-linux#115]
We have been attempting to run the intel wifi driver on the UEK kernel in Oracle Linux 9.3.   When I boot Oracle Linux 9.3 rhek, the intel wifi driver initilizes and runs correctly and you see the wifi device when running ipconfig.

When I run Oracle Linux 9.3 or 8.9 UEK, the wifi device doesn’t show up. 

If I manually modprobe the iwlwifi driver I get this on the terminal and 

```
Modprobe: error: COULD NOT INSERT ‘iwlwifi’: invalid argument
```
the following in the dmesg log: 

> [   13.311244] ------------[ cut here ]------------ 
> [   13.311246] WARNING: CPU: 5 PID: 1731 at net/netlink/genetlink.c:570 genl_validate_ops+0x1c5/0x278 
> [   13.311253] Modules linked in: cfg80211(+) intel_rapl_msr(+) x86_pkg_temp_thermal mei_me intel_powerclamp processor_thermal_device_pci(+) dell_smbios processor_thermal_device dell_wmi_sysman(+) dcdbas processor_thermal_rfim pcspkr i2c_designware_platform(+) i2c_i801 mei processor_thermal_mbox dell_wmi_descriptor wmi_bmof firmware_attributes_class i2c_designware_core thunderbolt(+) rfkill processor_thermal_rapl intel_hid i2c_smbus intel_rapl_common int3403_thermal int3400_thermal idma64 int340x_thermal_zone acpi_thermal_rel sparse_keymap acpi_pad acpi_tad fuse zram ext4 mbcache jbd2 loop vfat fat sd_mod sg i915 i2c_algo_bit drm_kms_helper crct10dif_pclmul crc32_pclmul syscopyarea sysfillrect sysimgblt ghash_clmulni_intel fb_sys_fops cec nvme ttm drm aesni_intel crypto_simd ucsi_acpi uas nvme_core cryptd usb_storage typec_ucsi typec t10_pi nvme_common wmi i2c_hid_acpi i2c_hid video pinctrl_tigerlake serio_raw btrfs blake2b_generic zstd_compress sunrpc lrw sha256_ssse3 dm_crypt 
> [   13.311280]  dm_round_robin dm_multipath dm_snapshot dm_bufio dm_mirror dm_region_hash dm_log dm_zero dm_mod linear raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq raid1 raid0 iscsi_ibft squashfs cramfs be2iscsi bnx2i cnic uio cxgb4i cxgb4 tls cxgb3i cxgb3 mdio libcxgbi libcxgb qla4xxx iscsi_boot_sysfs iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi 
> [   13.311295] CPU: 5 PID: 1731 Comm: systemd-udevd Not tainted 5.15.0-200.131.27.el9uek.x86_64 #2 
> [   13.311297] Hardware name: Dell Inc. Latitude 7430/07J3P7, BIOS 1.13.0 03/13/2023 
> [   13.311298] RIP: 0010:genl_validate_ops+0x1c5/0x278 
> [   13.311300] Code: d8 00 00 00 5b 5d 41 5c 41 5d 31 d2 31 c9 31 ff c3 cc cc cc cc 49 83 7c 24 50 00 0f 85 be fe ff ff 0f 0b b8 ea ff ff ff eb bc <0f> 0b b8 ea ff ff ff eb b3 0f 0b eb aa 0f 0b b8 ea ff ff ff eb a6 
> [   13.311302] RSP: 0018:ffff950d406a7c98 EFLAGS: 00010206 
> [   13.311303] RAX: 0000000000000003 RBX: ffff950d406a7d00 RCX: 0000000000000000 
> [   13.311304] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 0000000000000000 
> [   13.311305] RBP: 0000000000000001 R08: 0000000000000000 R09: 0000000000000000 
> [   13.311305] R10: 0000000000000000 R11: 0000000000000000 R12: ffffffffc145f920 
> [   13.311306] R13: ffff950d406a7c98 R14: 00007fba26dfe32c R15: ffff950d406a7e78 
> [   13.311307] FS:  00007fba260bd540(0000) GS:ffff89997f940000(0000) knlGS:0000000000000000 
> [   13.311308] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033 
> [   13.311309] CR2: 000055eba0681000 CR3: 0000000113250000 CR4: 0000000000750ee0 
> [   13.311310] PKRU: 55555554 
> [   13.311311] Call Trace: 
> [   13.311313]  <TASK> 
> [   13.311315]  ? show_trace_log_lvl+0x1d6/0x2f9 
> [   13.311319]  ? show_trace_log_lvl+0x1d6/0x2f9 
> [   13.311321]  ? 0xffffffffc12ad000 
> [   13.311323]  ? genl_register_family+0x25/0x1ef 
> [   13.311325]  ? genl_validate_ops+0x1c5/0x278 
> [   13.311327]  ? __warn+0x80/0x113 
> [   13.311329]  ? genl_validate_ops+0x1c5/0x278 
> [   13.311331]  ? report_bug+0xa4/0x11d 
> [   13.311334]  ? handle_bug+0x35/0x8b 
> [   13.311337]  ? exc_invalid_op+0x14/0x75 
> [   13.311338]  ? asm_exc_invalid_op+0x16/0x1b 
> [   13.311341]  ? genl_validate_ops+0x1c5/0x278 
> [   13.311343]  ? genl_validate_ops+0x94/0x278 
> [   13.311345]  ? __cfg80211_rdev_from_attrs+0x1d0/0x1d0 [cfg80211] 
> [   13.311384]  ? nl80211_dump_wiphy+0x1c0/0x1c0 [cfg80211] 
> [   13.311618]  ? nl80211_add_commands_unsplit+0x7d0/0x7d0 [cfg80211] 
> [   13.311648]  ? nl80211_send_wiphy+0x1c20/0x1c20 [cfg80211] 
> [   13.311679]  ? nl80211_register_unexpected_frame+0x60/0x60 [cfg80211] 
> [   13.311709]  ? 0xffffffffc12ad000 
> [   13.311710]  genl_register_family+0x25/0x1ef 
> [   13.311712]  ? 0xffffffffc12ad000 
> [   13.311713]  nl80211_init+0x13/0xcdc [cfg80211] 
> [   13.311751]  cfg80211_init+0x46/0xd9 [cfg80211] 
> [   13.311781]  do_one_initcall+0x54/0x1c6 
> [   13.311785]  do_init_module+0x4c/0x277 
> [   13.311787]  __do_sys_init_module+0x12e/0x1b4 
> [   13.311790]  do_syscall_64+0x38/0x8d 
> [   13.311793]  entry_SYSCALL_64_after_hwframe+0x64/0x0 
> [   13.311795] RIP: 0033:0x7fba26bcc69e 
> [   13.311798] Code: 48 8b 0d 85 a7 1b 00 f7 d8 64 89 01 48 83 c8 ff c3 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 49 89 ca b8 af 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 52 a7 1b 00 f7 d8 64 89 01 48 
> [   13.311799] RSP: 002b:00007ffe7184c048 EFLAGS: 00000246 ORIG_RAX: 00000000000000af 
> [   13.311800] RAX: ffffffffffffffda RBX: 000055eb9fc197f0 RCX: 00007fba26bcc69e 
> [   13.311801] RDX: 00007fba26dfe32c RSI: 000000000022c1f5 RDI: 000055eba0456df0 
> [   13.311802] RBP: 000055eba0456df0 R08: 000055eb9fc39380 R09: 000000000022c010 
> [   13.311803] R10: 0000000000000005 R11: 0000000000000246 R12: 00007fba26dfe32c 
> [   13.311803] R13: 000055eb9fba8b70 R14: 0000000000000007 R15: 000055eb9fba9230 
> [   13.311805]  </TASK> 
> [   13.311805] ---[ end trace 1b36ab559dbe3167 ]--- 
> [   13.314073] intel_rapl_common: Found RAPL domain package 
> [   13.314075] intel_rapl_common: Found RAPL domain core 
> [   13.314076] intel_rapl_common: Found RAPL domain uncore 
> [   13.314077] intel_rapl_common: Found RAPL domain psys 
> [   13.343329] input: Dell WMI hotkeys as /devices/platform/PNP0C14:02/wmi_bus/wmi_bus-PNP0C14:02/9DBB5994-A997-11DA-B012-B622A1EF5492/input/input7 
> [   13.515314] input: VEN_0488:00 0488:101A Mouse as /devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-2/i2c-VEN_0488:00/0018:0488:101A.0002/input/input8 
> [   13.515467] input: VEN_0488:00 0488:101A Touchpad as /devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-2/i2c-VEN_0488:00/0018:0488:101A.0002/input/input9 
> [   13.515647] hid-generic 0018:0488:101A.0002: input,hidraw0: I2C HID v1.00 Mouse [VEN_0488:00 0488:101A] on i2c-VEN_0488:00 
> [   13.516020] dell_laptop: Using i8042 filter function for receiving events 
> [   13.630296] input: VEN_0488:00 0488:101A Mouse as /devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-2/i2c-VEN_0488:00/0018:0488:101A.0002/input/input11 
> [   13.630388] input: VEN_0488:00 0488:101A Touchpad as /devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-2/i2c-VEN_0488:00/0018:0488:101A.0002/input/input12 
> [   13.630421] hid-multitouch 0018:0488:101A.0002: input,hidraw0: I2C HID v1.00 Mouse [VEN_0488:00 0488:101A] on i2c-VEN_0488:00 
> [  105.592534] ------------[ cut here ]------------ 
> 
> [  105.592537] WARNING: CPU: 0 PID: 2269 at net/netlink/genetlink.c:570 genl_validate_ops+0x1c5/0x278 
> [  105.592542] Modules linked in: cfg80211(+) libfc scsi_transport_fc joydev hid_multitouch dell_rbtn dell_laptop dell_wmi ledtrig_audio intel_rapl_msr x86_pkg_temp_thermal mei_me intel_powerclamp processor_thermal_device_pci dell_smbios processor_thermal_device dell_wmi_sysman dcdbas processor_thermal_rfim pcspkr i2c_designware_platform i2c_i801 mei processor_thermal_mbox dell_wmi_descriptor wmi_bmof firmware_attributes_class i2c_designware_core thunderbolt rfkill processor_thermal_rapl intel_hid i2c_smbus intel_rapl_common int3403_thermal int3400_thermal idma64 int340x_thermal_zone acpi_thermal_rel sparse_keymap acpi_pad acpi_tad fuse zram ext4 mbcache jbd2 loop vfat fat sd_mod sg i915 i2c_algo_bit drm_kms_helper crct10dif_pclmul crc32_pclmul syscopyarea sysfillrect sysimgblt ghash_clmulni_intel fb_sys_fops cec nvme ttm drm aesni_intel crypto_simd ucsi_acpi uas nvme_core cryptd usb_storage typec_ucsi typec t10_pi nvme_common wmi i2c_hid_acpi i2c_hid video pinctrl_tigerlake serio_raw 
> [  105.592566]  btrfs blake2b_generic zstd_compress sunrpc lrw sha256_ssse3 dm_crypt dm_round_robin dm_multipath dm_snapshot dm_bufio dm_mirror dm_region_hash dm_log dm_zero dm_mod linear raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq raid1 raid0 iscsi_ibft squashfs cramfs be2iscsi bnx2i cnic uio cxgb4i cxgb4 tls cxgb3i cxgb3 mdio libcxgbi libcxgb qla4xxx iscsi_boot_sysfs iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi 
> [  105.592580] CPU: 0 PID: 2269 Comm: modprobe Tainted: G        W         5.15.0-200.131.27.el9uek.x86_64 #2 
> [  105.592582] Hardware name: Dell Inc. Latitude 7430/07J3P7, BIOS 1.13.0 03/13/2023 
> [  105.592583] RIP: 0010:genl_validate_ops+0x1c5/0x278 
> [  105.592585] Code: d8 00 00 00 5b 5d 41 5c 41 5d 31 d2 31 c9 31 ff c3 cc cc cc cc 49 83 7c 24 50 00 0f 85 be fe ff ff 0f 0b b8 ea ff ff ff eb bc <0f> 0b b8 ea ff ff ff eb b3 0f 0b eb aa 0f 0b b8 ea ff ff ff eb a6 
> [  105.592586] RSP: 0018:ffff950d40e77c98 EFLAGS: 00010206 

> [  105.592587] RAX: 0000000000000003 RBX: ffff950d40e77d00 RCX: 0000000000000000 
> [  105.592588] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 0000000000000000 
> [  105.592588] RBP: 0000000000000001 R08: 0000000000000000 R09: 0000000000000000 
> [  105.592588] R10: 0000000000000000 R11: 0000000000000000 R12: ffffffffc145f920 
> [  105.592589] R13: ffff950d40e77c98 R14: 00005562b7ae3962 R15: ffff950d40e77e78 
> [  105.592590] FS:  00007fe7d8162740(0000) GS:ffff89997f800000(0000) knlGS:0000000000000000 
> [  105.592591] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033 
> [  105.592591] CR2: 00007fe7d7630000 CR3: 000000010f040000 CR4: 0000000000750ef0 
> [  105.592592] PKRU: 55555554 
> [  105.592593] Call Trace: 
> [  105.592594]  <TASK> 
> [  105.592596]  ? show_trace_log_lvl+0x1d6/0x2f9 
> [  105.592599]  ? show_trace_log_lvl+0x1d6/0x2f9 
> [  105.592601]  ? 0xffffffffc12a2000 
> [  105.592602]  ? genl_register_family+0x25/0x1ef 
> [  105.592603]  ? genl_validate_ops+0x1c5/0x278 
> [  105.592605]  ? __warn+0x80/0x113 
> [  105.592607]  ? genl_validate_ops+0x1c5/0x278 
> [  105.592608]  ? report_bug+0xa4/0x11d 
> [  105.592610]  ? handle_bug+0x35/0x8b 
> [  105.592613]  ? exc_invalid_op+0x14/0x75 
> [  105.592613]  ? asm_exc_invalid_op+0x16/0x1b 
> [  105.592616]  ? genl_validate_ops+0x1c5/0x278 
> [  105.592617]  ? genl_validate_ops+0x94/0x278 
> [  105.592619]  ? __cfg80211_rdev_from_attrs+0x1d0/0x1d0 [cfg80211] 
> [  105.592639]  ? nl80211_dump_wiphy+0x1c0/0x1c0 [cfg80211] 
> [  105.592656]  ? nl80211_add_commands_unsplit+0x7d0/0x7d0 [cfg80211] 
> [  105.592670]  ? nl80211_send_wiphy+0x1c20/0x1c20 [cfg80211] 
> [  105.592685]  ? nl80211_register_unexpected_frame+0x60/0x60 [cfg80211] 
> [  105.592700]  ? 0xffffffffc12a2000 
> [  105.592700]  genl_register_family+0x25/0x1ef 
> [  105.592702]  ? 0xffffffffc12a2000 
> [  105.592703]  nl80211_init+0x13/0xcdc [cfg80211] 
> [  105.592719]  cfg80211_init+0x46/0xd9 [cfg80211] 
> [  105.592743]  do_one_initcall+0x54/0x1c6 
> [  105.592747]  do_init_module+0x4c/0x277 
> [  105.592749]  __do_sys_init_module+0x12e/0x1b4 
> [  105.592751]  do_syscall_64+0x38/0x8d 
> [  105.592753]  entry_SYSCALL_64_after_hwframe+0x64/0x0 
> [  105.592755] RIP: 0033:0x7fe7d81a669e 
> [  105.592756] Code: 48 8b 0d 85 a7 1b 00 f7 d8 64 89 01 48 83 c8 ff c3 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 49 89 ca b8 af 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 52 a7 1b 00 f7 d8 64 89 01 48 

> [  105.592757] RSP: 002b:00007fffc49482e8 EFLAGS: 00000246 ORIG_RAX: 00000000000000af 
> [  105.592758] RAX: ffffffffffffffda RBX: 00005562b8e5efa0 RCX: 00007fe7d81a669e 
> [  105.592759] RDX: 00005562b7ae3962 RSI: 000000000022c1f5 RDI: 00007fe7d7404010 
> [  105.592759] RBP: 00007fe7d7404010 R08: 00005562b8e5f6a0 R09: 000000000022d000 
> [  105.592760] R10: 0000000000000005 R11: 0000000000000246 R12: 00005562b7ae3962 
> [  105.592760] R13: 00005562b8e5ef40 R14: 00005562b8e5efa0 R15: 00005562b8e5f650 
> [  105.592761]  </TASK> 
> [  105.592762] ---[ end trace 1b36ab559dbe3168 ]--- 

I have tried this on these laptops with the same results: 

Intel AX211 wifi 
- DELL Latitude 7430 
- HP Zbook Power 15.6 G10 

Intel AX201 wifi 
- HP Elitebook x360 1040 G7 

When running on the RHEK kernel all of them correctly recognize the wifi adaptor on boot. 

To reproduce the problem, download the Oracle Linux Boot ISO and burn it to a flash drive.  Boot using troubleshooting mode and exit to the shell 

On UEK try ifconfig and look for the wifi device.  If none is found, then use modprobe iwlwifi to load the driver. 

On the uek kernel you will see the message 

Modprobe: error: COULD NOT INSERT ‘iwlwifi’: invalid argument 

And the dmesg log will show the stack trace above. 

The following full logs are from a DELL Latitude 7430  they are similar for the other laptops

Working log from the rhek kernel
[rhek-9.3-iwlwifi.txt](https://github.com/oracle/oracle-linux/files/13638987/rhek-9.3-iwlwifi.txt)
UEK kernel log with stack trace on Oracle Linux 8.9
[uek-8.9-iwlwifi.txt](https://github.com/oracle/oracle-linux/files/13638988/uek-8.9-iwlwifi.txt)
UEK kernel log with stack trace on Oracle Linux 9.3
[uek-9.3-iwlwifi.txt](https://github.com/oracle/oracle-linux/files/13638989/uek-9.3-iwlwifi.txt)

**Comment by totalamateurhour** [comment]
do you have `kernel-uek-modules` installed?

**Comment by bah-mikerosenblum** [comment]
Yes

**Comment by totalamateurhour** [comment]
In the UEK case, what's the output of `rpm -qa | grep iwl`

**Comment by totalamateurhour** [comment]
I suspect the issue stems from the fact you are using the boot ISO. That may not have all you need to get wifi working.

**Comment by bah-mikerosenblum** [comment]
rpm -qa | grep iwl shows nothing.  It is interesting that the RHEK kernel boot iso works fine.  I came across this issue when running on a normal installation.  I wanted to use the UEK kernel but ran into this problem, then moved to the RHEK kernel using the same kickstart file, so I think I have everything installed for wifi.  It is at the driver level so it shouldn't require much else.

**Comment by tvierling** [comment]
This was fixed in the latest UEK7 kernels (5.15.0); update and you should be good to go.

**Comment by bah-mikerosenblum** [comment]
I re-tested  the original problem report on the 9.3 uek iso from https://yum.oracle.com/oracle-linux-isos.html and it still fails in the same way as initially described in this problem report.  The kernel version from the dmesg log is 


[    0.000000] Linux version 5.15.0-200.131.27.el9uek.x86_64 (mockbuild@host-100-100-224-30) (gcc (GCC) 11.3.1 20221121 (Red Hat 11.3.1-4.3.0.4), GNU ld version 2.35.2-37.0.2.el9) #2 SMP Wed Oct 4 22:09:54 PDT 2023

The full dmsg log including the oops from running modprobe iwlwifi is attached below

[dmesg_uek_9.3.log](https://github.com/oracle/oracle-linux/files/13955291/dmesg_uek_9.3.log)

**Comment by scoter-oracle** [comment]
Hi @bah-mikerosenblum , can you please update your system through "dnf update" ? As of today you should get on the following UEK7 release:

5.15.0-202.135.2.el9uek

and the same should include the fix needed on your environment.
Please, let us know.

**Comment by bah-mikerosenblum** [comment]
Thanks, that did the trick
